spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML5

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lakerhome?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5

server:
  port: 8080
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mapper/config/mybatis-config.xml
  type-aliases-package: com.ciper.lakerhome.entity

#在spring中指定了mybatis的配置文件就不能在spring中对mybatis进行配置
#Property 'configuration' and 'configLocation' can not specified with together